### ISSUE TITLE
descriptions do not show

### ISSUE THREAD

**Issue by ftoledo** [propush/hdpntreqlist#7]
Hi!
I build a list with the echos at:

https://bbs.docksud.com.ar/hde_areas

On subscription screen at hotdoged i do not see the descriptions (I can see the date and message count: 

example: 
![imagen](https://user-images.githubusercontent.com/95441/79967476-44db2f80-8465-11ea-8dfd-582f005f1793.png)

Have the list a bad format?

thanks!

**Comment by propush** [comment]
Sorry, I guess description parsing was not yet implemented. Your file is fine.

**Comment by ftoledo** [comment]
Ok!! thanks! i just asumed that the descriptions are supported today!

I will wait for it! thanks!
